version: "2"
services: 
   db:
      image: neo4j:3.0
      environment:
         - NEO4J_AUTH=neo4j/password
      ports:
         - 7474:7474
         - 7687:7687
         
   web:
      image: springboot-neo4j
      depends_on: 
         - db
      ports:
         - 8085:8085